build.gradle, gradle.properties
We need the ability to control the version number we want to publish differently between internal and external builds. gradle.properties isn't so easy to override via an adapt script in internal builds. Changing it to using specific configuration in jar tasks seems to be doing the trick. Tested both in this build and internally.
=> Change the way of specifying jar versions

photon-ml/src/integTest/scala/com/linkedin/photon/ml/DriverIntegTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/Evaluation.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/constants/MathConst.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/AreaUnderROCCurveLocalEvaluator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/BinaryClassificationEvaluator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/Evaluator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/LocalEvaluator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/LogisticLossEvaluator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/SquaredLossEvaluator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/projector/RandomEffectProjector.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/sampler/DefaultDownSampler.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/evaluation/AreaUnderROCCurveLocalEvaluatorTest.scala
As discussed in issue #42, currently the only AUC computation supported in Photon/GAME is ```RDD``` based, e.g., the input scores and labels are in the ```RDD[(Double, Double)]``` format.
However, in order to enable per random effect AUC computation as in issue #41, computing AUC locally in the ```Array[(Double, Double)]``` or ```Seq[(Double, Double)]``` format will be a useful feature to have.
Besides, the local AUC computation will be helpful to our effort in evaluating different matrix factorization packages as well.
One more change made in this PR is that, now the local AUC computation will take the weight of each data point into consideration when computing AUC.
=> Adding local AUC computation to the evaluation package

photon-ml/src/integTest/scala/com/linkedin/photon/ml/avro.model/ModelProcessingUtilsTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/AvroUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/model/ModelProcessingUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/VectorUtils.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/avro/AvroUtilsTest.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/util/VectorUtilsTest.scala
As discussed in Issue #45, it would be helpful if the coefficients type can be flexible when loaded from Avro model file, instead of always being a ```DenseVector[Double]```, for example, the coefficient type could be either dense vector or sparse vector based on the sparsity of the underlying array. 
This will be helpful in cases when the underlying dimension of the coefficient space (array length) is large, but the actual support (active size) is small.
Also some unit tests are added in this PR.
=> Coefficients type should be flexible when loaded from Avro model file

.travis.yml, build.gradle, photon-ml/src/integTest/scala/com/linkedin/photon/ml/util/PhotonLoggerIntegTest.scala, tests.sh
- Modified PhotonLoggerIntegTest to have a more accurate regex (previously it assumed the time zone would always be West of GMT)
- Added custom script for testing on Travis CI
- Split unit tests and integration tests to run in parallel
- Integration test output is redirected to a tmp file, to get around the 4MB log file size issue. Setup up a dummy process to ping Travis every 30s so it doesn't kill the test process for inactivity. Dump the last 500 lines whenever tests complete successfully or an error occurs.
Much of the script comes from here:
http://stackoverflow.com/questions/26082444/how-to-work-around-travis-cis-4mb-output-limit
=> Enable integration tests on Travis CI

photon-ml/src/main/scala/com/linkedin/photon/ml/util/IOUtils.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/util/IOUtilsTest.scala
The current implementation uses DataOutputStream.writeBytes interface which casts char to byte and write only one byte per char. 
`   public final void writeBytes(String s) throws IOException {
int len = s.length();
for (int i = 0 ; i < len ; i++) {
out.write((byte)s.charAt(i));
}
incCount(len);
}
`
But Java char uses UTF encoding so sizeof(char) = 2 bytes (https://docs.oracle.com/javase/8/docs/api/java/lang/Character.html) and the casting will cause troubles for international languages used in feature names and terms.
=> Fix utf8 string output in IOUtils

photon-ml/src/main/scala/com/linkedin/photon/ml/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/SparkContextConfiguration.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala
This PR addresses #64. This should serve as a temporary fix for this problem, in the long run, we may want to have the log level for Photon and Spark to be configurable. @ashelkovnykov, I added a few TODOs in the code, do you think we can take them into account during our Photon/GAME refactoring?
=> Set the default Photon log level to DEBUG

photon-ml/src/main/scala/com/linkedin/photon/ml/io/GLMSuite.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/io/GLMSuiteTest.scala, photon-test/src/main/scala/com/linkedin/photon/ml/test/CommonTestUtils.scala
This pull request addresses the following two issues:
* A bug in box constraints where we'd incorrectly treat two features as identical if there was a substring match between the feature names
* A minor issue where we'd allow users to specify empty constraints (e.g. for typos in upperBound, lowerBound or both)
=> Fix feature name collision / strictness issues in box constraints

photon-ml/src/integTest/scala/com/linkedin/photon/ml/data/KeyValueScoreTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/model/FixedEffectModelTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/model/MatrixFactorizationModelTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/model/RandomEffectModelTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/data/GameDatum.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/data/KeyValueScore.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/model/MatrixFactorizationModel.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/sampler/DownSampler.scala
The motivation of this PR is to address #59 by adding MatrixFactorizationModel to GAME's model package.
In order to write integration tests for matrix factorization model, a few other tweaks are made in this PR with each corresponds to a commit:
1. Making GameDatum serializable
2. Change the scope of some functions in DownSampler.scala
3. Add the equals function to KeyValueScore, also added integTest for it as well as some other existing functions in KeyValueScore
4. Minor tweaks to the existing integTest for fixed and random effect models
5. Address #59 by adding MatrixFactorizationModel to GAME's model package, and added integTest for it.
=> Adding MatrixFactorizationModel to GAME's model package, with other relevant integTest improvement.

photon-ml/src/main/scala/com/linkedin/photon/ml/avro/AvroUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/data/DataProcessingUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/Utils.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/util/UtilsTest.scala
This PR changes the default value for ```isNullOK``` to false, in order to make it consistent with other ```get*Avro``` functions.
This PR also makes sure that ```getFeatureKey``` and ```readNameAndTermFromGenericRecord``` functions are sharing the same the same logic, which is that the term is allowed to be null.
See #77 for more details.
=> Changing the default value for isNullOk to false.

photon-ml/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/DriverGameIntegTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Params.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/io/FieldNamesType.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/io/ModelOutputMode.scala
Addresses issue #84.
Tested on the LinkedIn internal grid. With 'save-models-to-hdfs' set to false, only the best model was output.
=> Deprecate 'save-models-to-hdfs'. Add new parameter to control model output.

build-scripts/integration-test.gradle, build.gradle, photon-ml/src/integTest/scala/com/linkedin/photon/ml/util/IOUtilsIntegTest.scala, photon-test/src/main/scala/com/linkedin/photon/ml/test/FailOnSkipListener.scala
TestNG was skipping this test because the DataProvider failed to create a null date range.
This PR also includes a change that would prevent this from happening in the future. The idea is to globally transform all tests that are skipped on account of a Throwable into failures.
=> Fix skipped test

photon-ml/src/integTest/scala/com/linkedin/photon/ml/util/IOUtilsIntegTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/data/NameAndTermFeatureSetContainer.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/IOUtils.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/util/UtilsTest.scala
Currently Photon/GAME will silently delete the user specified output directory if it exists. However, such behavior is inconsistent with Pig and Spark, where an exception will be thrown if the output directory exists.
More details on this PR are discussed in #87.
=> Throw exception if output directory already exists.

photon-ml/src/integTest/scala/com/linkedin/photon/ml/util/IOUtilsIntegTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/DateRange.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/util/DateRangeTest.scala
As discussed in issue #91, it is useful to allow the start date and end date to be configured as the same day in certain use cases.
=> Allow the start date and end date to be configured as the same day

photon-ml/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/DriverGameIntegTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/BinaryClassificationEvaluator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/Evaluator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/LogisticLossEvaluator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/RMSEEvaluator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/SquaredLossEvaluator.scala
This addresses issue https://github.com/linkedin/photon-ml/issues/93
Previously we selected the "best" model by largest score value. This is
wrong for some metrics, however, such as RMSE where larger values
indicated greater error.
The fix is a change to the Evaluator interface that allows evaluator
implementations to specify how scores should be compared.
=> Fix GAME model selection logic bug

photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/Optimizer.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/TRON.scala
As discussed in #98, this PR removes the unnecessary logging in ```optimizer```, and also changes the log level in ```Tron``` from info to debug.
=> Remove unnecessary logging in optimizer

photon-ml/src/main/scala/com/linkedin/photon/ml/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/AbstractOptimizer.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/LBFGS.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/OptimizationStatesTracker.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/Optimizer.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/OptimizerState.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/TRON.scala
When investigating some of the issues that our Photon ML customers encountered recently, I found the following logs from the model training job:
number of training data points: 25250560, number of features in **each** training example including intercept (if any) 3479.
Convergence reason: objective is not improving
Iter   Time(s)                    Value     |Gradient|
0     1.607        37800195.11474618       1.18e+07
1    21.362        35780206.30930489       1.52e+07
2    28.717        35490290.19306723       1.95e+06
**3    50.755        35224190.91374312       1.94e+06
3    69.871        35224190.91374312       1.94e+06**
Highlighted are two problems I found:
The first is the misleading statement on the feature size, what we really want to inform the user is that "**total** number …
=> Fix the bugs identified through Photon model training logs

README.md
And add some simple notes on how to run Photon ML on other cluster modes.
This is a follow up PR of issue #76.
=> Make it explicit that the example scripts are for Yarn.

photon-ml/src/integTest/scala/com/linkedin/photon/ml/DriverIntegTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/io/GLMSuiteIntegTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/io/GLMSuite.scala
A quick fix for the issue reported by Photon users at LinkedIn.
Problem description:
When the input data are represented in the Avro format, data point with empty feature bag will not be used for model training.
And such logic is problematic, for example, if a data set used for model training only contains one binary feature, with each data point that contains such feature being treated as feature with value 1 and data point that doesn't contain such feature (missing feature) being treated as feature with value 0, the logic described above will throw away all the data points with missing feature and only data points with feature value 1 will kept for model training. As a result, the learned model will be wrong.
Integration tests updated to cover the fixed bug.
=> Fix the bug where data point with empty feature bag being thrown away in Photon's GLMSuite

photon-ml/src/integTest/scala/com/linkedin/photon/ml/DriverIntegTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/MockDriver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/OptionNames.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/Params.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/PhotonMLCmdLineParser.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/diagnostics/DiagnosticMode.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/diagnostics/reporting/reports/model/ModelDiagnosticReport.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/diagnostics/reporting/reports/model/ModelDiagnosticToPhysicalReportTransformer.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/PhotonMLCmdLineParserTest.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/diagnostics/DiagnosticStatus.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/diagnostics/DiagnosticStatusTest.scala
This PR addresses issue #118 by allowing the users to specify which mode (all, none, train, validate) of diagnostic is needed in Photon's driver.
In order to achieve this goal, some refactoring is also done for the diagnostics module in Photon.
One interesting side-effect of this PR I observed is that, the integTest runtime got further reduced (issue #19) due to the more fine grained control over model diagnostic. And after this PR, it is expected that the overall runtime of Photon's GLM model training will also be reduced if the diagnostic mode is chosen to better reflect the user's need.
This PR also addresses an internal issue ML-1273.
=> Major refactoring for the diagnostics module in Photon's driver

photon-ml/src/main/scala/com/linkedin/photon/ml/Driver.scala
The same line appears 5 lines below here. This duplicate was causing a
bug where we call "trainingData.first()" before checking whether
"trainingData" is empty.
=> Remove extra calculation of feature number

photon-ml/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/DriverTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Params.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/function/LogisticLossFunction.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/function/PoissonLossFunction.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/function/SquaredLossFunction.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/normalization/NormalizationContext.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/GeneralizedLinearOptimizationProblem.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/LinearRegressionOptimizationProblem.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/LogisticRegressionOptimizationProblem.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/PoissonRegressionOptimizationProblem.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/SmoothedHingeLossLinearSVMOptimizationProblem.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/game/FactoredRandomEffectOptimizationProblem.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/game/GLMOptimizationConfiguration.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/game/RandomEffectOptimizationProblem.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/cli/game/training/ParamsTest.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/optimization/LinearRegressionOptimizationProblemTest.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/optimization/LogisticRegressionOptimizationProblemTest.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/optimization/PoissonRegressionOptimizationProblemTest.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/optimization/SmoothedHingeLossLinearSVMOptimizationProblemTest.scala
PR for issue #128. It's smaller than it looks, there are a few style changes as well (now using the [Spark style guide](https://github.com/databricks/scala-style-guide)).
**UPDATE:** A test on the cluster confirms that variance information is now being output.
=> Enable coefficient variance computation

README.md
This adds a section with instructions for running the tutorial docker image to the README
=> Add docker instructions to README

photon-ml/src/main/scala/com/linkedin/photon/ml/util/DefaultIndexMap.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/util/DefaultIndexMapTest.scala
Previously there was no implementation for "DefaultIndexMap.size", so
the runtime fell back to the "size" implementation in TraversableOnce,
which iterates over the collections of entries each time. Since the
backing map "featureNameToIdMap" is immutable, we can assume that its
size never changes, and cache the size when it's passed in.
=> Fix scalability issue with DefaultIndexMap.size

photon-ml/src/main/scala/com/linkedin/photon/ml/avro/AvroFieldNames.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/data/DataProcessingUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/Utils.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/avro/data/DataProcessingUtilsTest.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/util/UtilsTest.scala
This change will allow randomEffectId fetching to fall back to metadataMap if
a key is not present in the Avro field directly. This will make the Avro schema
a bit more flexible in the sense that users won't necessarily to change Avro
schema definition when changing the set of ids provided for training.
Addressing #156 , I modified `Utils` and added corresponding tests for reading a map. Could anyone help point me to the doc location for explaining the Avro input format, I didn't find it's explained in param parser? ...
to: @joshvfleming @XianXing @ashelkovnykov 
**Another thing:**
I'd like to introduce @jq (Julian Qian) to everyone. He is my current colleague at Airbnb Pricing team. We are starting on some experiments using Photon GAME in our models; things are still at an early stage …
=> Issue#156: allowing randomEffectId fetching in metadatMap as an option

photon-ml/src/integTest/scala/com/linkedin/photon/ml/avro/ScoreProcessingUtilsTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/FieldNames.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/data/DataProcessingUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/data/ScoreProcessingUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/avro/data/DataProcessingUtilsTest.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/data/GAMEDatumTest.scala
Sorry folks, here is another PR to address some PROD issues caused by PR #166.
The main problem is that, previously GAME's scoring module would automatically find a field call "uid" in the scoring data and populate it to the scoring results in the format of ```ScoringResultAvro```. However, with PR #166, the users are required to instruct GAME to look for the "uid" field explicitly, otherwise the "uid" field in ```ScoringResultAvro``` would be null by default, which is not backward compatible and will break things.
Now with the fix proposed in this PR, "uid" will be added automatically to ```GameDatum``` again with GAME scoring job.
I really look forward to the upcoming Photon client redesign and refactoring, which should make our life easier :)
=> Bug fix: make GAME scoring backward compatible.

photon-ml/src/main/scala/com/linkedin/photon/ml/avro/data/DataProcessingUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/avro/data/DataProcessingUtilsTest.scala
Sorry folks, another PR for to make Photon-ML backward compatible.
Lesson learned: I didn't realize that the naming of parameters of Scala's functions (not the naming of the function or the signature of the function) would lead to such compatibility issues. Need to be more careful next time.
=> Revert function argument name to make it backward compatible.

photon-ml/src/main/scala/com/linkedin/photon/ml/avro/AvroUtils.scala
In cases with very many (90+) input files, we were getting a stack
overflow error here because of the long RDD lineage resulting from
unioning the RDDs one-by-one. This should address
the problem by producing a flat lineage.
=> Use sc.union to union RDDs from multiple files

photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/LogisticLossEvaluator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/PoissonLossEvaluator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/SmoothedHingeLossEvaluator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/SquaredLossEvaluator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/function/HessianDiagonalAggregator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/function/HessianVectorAggregator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/function/ValueAndGradientAggregator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/function/glm/LogisticLossFunction.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/function/glm/PointwiseLossFunction.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/function/glm/PoissonLossFunction.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/function/glm/SquaredLossFunction.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/function/svm/SmoothedHingeLossFunction.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/function/LogisticLossFunctionTest.scala
This change was suggested by Frank for PR #131, but I forgot to add it.
=> Change differentiation function names to follow Euler's notation

photon-avro-schemas/src/main/avro/BayesianLinearModelAvro.avsc
This was previously generating a warning, since "string" cannot be null.
=> Fix type of "modelClass" in BayesianLinearModelAvro

photon-ml/build.gradle
We don't use this, and it causes version conflicts in downstream projects.
=> Exclude netty from dependency on avro-mapred

README.md
the correct way to install Spark on OS X
=> Update README: brew install spark => apache-spark

photon-ml/src/integTest/scala/com/linkedin/photon/ml/avro/ModelProcessingUtilsTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/model/GAMEModel.scala
Calling zip directly on maps doesn't zip on keys but just zips the underlying (key, value) iterables. So our current test is incorrect
=> Fix map zipping bug in ModelProcessingUtilsTest

photon-client/src/main/scala/com/linkedin/photon/ml/avro/model/ModelProcessingUtils.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/TaskType.scala
When loading old models without metadata, we should accept them as long as all of the sub-models have consistent type.
=> Patch to keep model loading backwards compatible.

photon-client/src/integTest/scala/com/linkedin/photon/ml/estimators/GameEstimatorTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-lib/src/integTest/scala/com/linkedin/photon/ml/stat/BasicStatisticalSummaryTest.scala
In Spark 2.1, when you map over a DataFrame/Dataset, it tries to do an implicit lookup of the approriate encoder for the row type. This fails in our case, because we have no such encoder. Mapping over the rdd view of the DataFrame/Dataset gets around this issue.
=> Fix Spark 2.1 compatibility issues

photon-api/src/main/scala/com/linkedin/photon/ml/optimization/game/FactoredRandomEffectOptimizationConfiguration.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/game/GameModelOptimizationConfiguration.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/estimators/GameEstimatorTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/estimators/GameEstimator.scala, photon-client/src/main/scala/com/linkedin/photon/ml/estimators/GameParams.scala, photon-client/src/test/scala/com/linkedin/photon/ml/estimators/GameParamsTest.scala
In some cases (e.g. hyperparameter tuning) we need programmatic access to the configuration of the Game optimizers for a trained model. This exposes those settings in a struct and provides `toString` for the previous usages.
=> Store per-model Game config snapshots in a struct rather than String

photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Driver.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/constants/StorageLevel.scala
Based on experiments, changing levels of RDDs in scoring driver as follows:
1. gameDataSet: disk_only
2. gameModel: memory_only
3. scores: memory_and_disk
=> Change caching levels of RDDs

photon-client/src/integTest/scala/com/linkedin/photon/ml/DriverTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/Driver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/estimators/GameParams.scala, photon-client/src/main/scala/com/linkedin/photon/ml/io/deprecated/GLMSuite.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/util/Implicits.scala
We had a case where the weights for all the training samples were zero, causing the optimizer to not even start. 
This PR introduces code to check that the weights are all >= 0 and that at least one is > 0. Since this test could be costly, there is a new boolean parameter (`checkData`) to turn this check on or off.
=> Verifying sample weights for training and validation data (optionally)

photon-api/src/main/scala/com/linkedin/photon/ml/algorithm/RandomEffectCoordinate.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/FixedEffectDataSet.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/RandomEffectDataSet.scala, photon-api/src/main/scala/com/linkedin/photon/ml/model/MatrixFactorizationModel.scala, photon-api/src/main/scala/com/linkedin/photon/ml/model/RandomEffectModel.scala, photon-api/src/main/scala/com/linkedin/photon/ml/model/RandomEffectModelInProjectedSpace.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/RandomEffectOptimizationTracker.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/game/GameModelOptimizationConfiguration.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/game/RandomEffectOptimizationProblem.scala, photon-api/src/main/scala/com/linkedin/photon/ml/projector/IndexMapProjectorRDD.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/estimators/GameEstimator.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/data/scoring/DataScores.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/optimization/Optimizer.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/spark/RDDLike.scala
- The RandomEffectOptimizationTracker was initialized using OptimizationStateTrackers the RDD of SingleNodeOptimizationProblems stored in a RandomEffectOptimizationProblem after optimization - however, this RDD is persisted to disk, so it was pulling the trackers in their original empty state
- Added a 'smartMaterialize' method to the RDDLike trait to only materialize unmaterialized RDDs
These changes had no significant impact on performance locally (5 second speed-up on a  16 minute job). Performance tests on the cluster did not reveal any significant performance change(+/- 100 seconds of training for a 90 minute job with 50 minutes of training).
=> Fix bug that incorrectly logged all random effect models as not converging

photon-all/build.gradle, photon-avro-schemas/src/main/avro/BayesianLinearModelAvro.avsc, photon-avro-schemas/src/main/avro/LatentFactorAvro.avsc, photon-avro-schemas/src/main/avro/NameTermValueAvro.avsc, photon-client/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/DriverTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/avro/AvroUtils.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/avro/ModelProcessingUtils.scala
These changes were approved once as part of another commit but pulled out to keep Photon backwards compatible temporarily for LI internal reasons.
=> Make namespace consistent for photon schemas and stop shading avro schemas

photon-api/src/main/scala/com/linkedin/photon/ml/data/GameConverters.scala, photon-api/src/main/scala/com/linkedin/photon/ml/estimators/GameEstimator.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/DriverTest.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/data/GameConvertersTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Driver.scala
If the records being scored have an identity, we currently lose that information after scoring except via the UID field, if one exists.
If one wants to preserve some meta information about the record, this PR adds a way of doing this. The user can add simple flags that they want to preserve in the metadata map and after scoring the map in the output will preserve all fields in the input metadata map and add to them, information about the random effect ids. Before this PR, the metadata map in the output would only contain the random effect id information and the input metadata map would be ignored.
=> Add a way to preserve metadata map in the input records after scoring

photon-api/src/main/scala/com/linkedin/photon/ml/data/RandomEffectDataSetInProjectedSpace.scala, photon-api/src/main/scala/com/linkedin/photon/ml/model/RandomEffectModelInProjectedSpace.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/algorithm/CoordinateDescent.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/algorithm/CoordinateDescentTest.scala
This bug has been giving us trouble. I've tested the solution internally, in addition to the unit and integration tests.
Prior to the patch, we were unpersisting the coordinates of the trained GAME model (stored in `updatedGameModel`) each time we computed a new one.
This caused an issue in the case that an iteration produced a worse overall model - the coordinate models that made up the GAME model had been unpersisted. When the best GAME model is returned and used, Spark would try to recompute the coordinate models using their lineage. However, since the `GameEstimator` had already unpersisted the training data, it would try to recompute that as well. For very large datasets, recomputing the training data potentially means doing reservoir sampling and limiting features by Pearson …
=> Fix bug that would unpersist models that are still in use

.gitignore, build.gradle, photon-api/build.gradle, photon-api/src/integTest/scala/com/linkedin/photon/ml/algorithm/FixedEffectCoordinateIntegTest.scala, photon-api/src/integTest/scala/com/linkedin/photon/ml/supervised/BaseGLMTest.scala, photon-avro-schemas/build.gradle, photon-client/build.gradle, photon-client/src/integTest/scala/com/linkedin/photon/ml/data/DataValidatorsIntegTest.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/data/avro/AvroDataReaderIntegTest.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/data/avro/AvroUtilsIntegTest.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/io/deprecated/GLMSuiteIntegTest.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/util/IOUtilsIntegTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/DataValidators.scala, photon-diagnostics/build.gradle, photon-diagnostics/src/integTest/scala/com/linkedin/photon/ml/BootstrapTrainingIntegTest.scala, photon-lib/build.gradle, photon-lib/src/integTest/scala/com/linkedin/photon/ml/optimization/OptimizerIntegTest.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/algorithm/CoordinateDescent.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/optimization/OptimizerTest.scala, photon-test-utils/build.gradle
- Renamed integration tests that had the same name as their unit tests counterparts
- Changed the location of Java classes generated from Avro schemas to be within the `photon-avro-schemas` module
- Minor comment and logging changes
=> Minor changes so that Photon-ML compiles within IntelliJ IDEA

photon-all/build.gradle
The failure was being caused by relocating the Snappy classes when building the shaded jar. Snappy includes native libraries that speed up the compression / decompression process. After relocation, it can't find the native libraries anymore. This change could potentially cause conflicts with other versions of Snappy on the classpath, but it doesn't work at all in its current state.
=> Fix failure when reading Snappy-compressed avro data

photon-api/src/main/scala/com/linkedin/photon/ml/estimators/GameEstimator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/projector/IdentityProjector.scala, photon-api/src/main/scala/com/linkedin/photon/ml/projector/RandomEffectProjector.scala
Previously the code assumed that we're doing a factored random effect problem for identity projections. This would cause a failure when it tried to load from a nonexistent factored random effect configuration. This commit adds a dedicated identity projector and selects it when the IDENTITY projection option is selected.
=> Enable identity projection

photon-api/src/main/scala/com/linkedin/photon/ml/projector/IndexMapProjector.scala, photon-api/src/test/scala/com/linkedin/photon/ml/projector/IndexMapProjectorTest.scala
The idea behind building this projecting mapping is that we can reduce feature dimensionality for a RE problem if there are features in the full space that are all zeros in the RE sub-problem. The previous method used "activeKeysIterator" for this, but for DenseVector, this method just returns all indices. Hence reduction was never happening.
=> Fix issue where IndexMapProjector incorrectly projects dense vectors

photon-api/src/integTest/scala/com/linkedin/photon/ml/projector/IndexMapProjectorRDDTest.scala, photon-api/src/main/scala/com/linkedin/photon/ml/projector/IndexMapProjector.scala, photon-api/src/main/scala/com/linkedin/photon/ml/projector/IndexMapProjectorRDD.scala, photon-api/src/test/scala/com/linkedin/photon/ml/projector/IndexMapProjectorTest.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/util/VectorUtils.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/util/VectorUtilsTest.scala
Previously we were scanning only the active data to determine the nonzero indices of a RE dataset. This can produce nondeterministic results when we recompute and resample the active data, because the dimensionality of the feature vectors can change and get out of sync with the model.
The fix is to scan both active and passive data to determine the feature projection.
=> Fix issue where IndexMapProjector produces nondeterministic results

photon-client/src/main/scala/com/linkedin/photon/ml/data/avro/AvroUtils.scala
We are trying to use Photon-ML with the training data, output directory and feature path stored in S3 instead of in HDFS. When using photon-ml with s3 I am getting the following error:
2017-09-12T18:54:02.273+0000 [ERROR] Failure while running the driver
java.lang.IllegalArgumentException: Wrong FS: s3://com.climate.qa1.analytics/dsw/data/staging/v2.1/blup/out/all/0/fixed-effect/fixed/coefficients/part-00000.avro, expected: hdfs://ip-172-16-130-18.ec2.internal:8020
at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:653)
=> https://github.com/linkedin/photon-ml/issues/301- Issue with writing to S3 from Photon-ML

photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/search/GaussianProcessSearch.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/search/RandomSearch.scala
Sobol generators produce approximately equidistant points, which cover the space better than a simple uniform distribution. With this change, the EI acquisition function appears less likely to get stuck in local optima in experiments. Hence we also switch to EI prediction transformation so that there's no need to specify an exploration parameter as with UCB.
=> Change hyperparameter candidate generation to a Sobol generator

photon-api/src/integTest/scala/com/linkedin/photon/ml/estimators/GameEstimatorIntegTest.scala, photon-api/src/main/scala/com/linkedin/photon/ml/algorithm/FixedEffectCoordinate.scala, photon-api/src/main/scala/com/linkedin/photon/ml/estimators/GameEstimator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/DistributedOptimizationProblem.scala, photon-api/src/test/scala/com/linkedin/photon/ml/estimators/GameEstimatorTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/io/scopt/game/ScoptGameTrainingParametersParser.scala, photon-client/src/test/scala/com/linkedin/photon/ml/io/scopt/game/ScoptGameTrainingParametersParserTest.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/algorithm/CoordinateDescent.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/optimization/Optimizer.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/algorithm/CoordinateDescentTest.scala
- Introduced configurable parameter to re-use trained GameModel objects as a starting point for training further GameModels
- Note: GAME already uses warm-start training during coordinate descent (the way the legacy Photon code does)
- Added unit test for GameEstimator
- Fixed bug in GameEstimator.copy
=> Enable option to use warm-start training for GAME

photon-client/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriverIntegTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/avro/AvroUtils.scala
Final step to move all references to the very LinkedIn-specific NameAndTerm into the AvroUtils.
=> Move reference to NameAndTerm class out of GameTrainingDriverIntegTest.

Photon Style.xml
To make it easier for users who wish to contribute to Photon ML, we should have a style file which can be plugged into IntelliJ, for example.
Photon ML uses a combination of the [Scala style](http://docs.scala-lang.org/style/) and the [Databricks style](https://github.com/databricks/scala-style-guide) guides.
=> Add Photon ML style document to repo

photon-api/src/main/scala/com/linkedin/photon/ml/data/GameConverters.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/data/avro/AvroDataReaderIntegTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/avro/AvroDataReader.scala, photon-client/src/test/scala/com/linkedin/photon/ml/data/avro/AvroDataReaderTest.scala, photon-lib/src/integTest/scala/com/linkedin/photon/ml/stat/BasicStatisticalSummaryTest.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/stat/BasicStatisticalSummary.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/util/VectorUtils.scala
New Vector interfaces have been introduced in spark.ml (presumably to replace the spark.mllib interfaces). This change upgrades us to the new interfaces, and fixes a bug where DataFrames produced from AvroDataReader didn't work with estimators in spark.ml.
=> Upgrade to Vector interfaces in spark.ml

photon-client/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriverIntegTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriver.scala
- Added comment explaining problem and temporary solution
- Added new unit test for hyper-parameter tuning which doubles as test for evaluator mismatch error
- Replace hard-coded names with references to constants in the GameTrainingDriverIntegTest
=> Patch to fix evaluator mismatch error

photon-api/src/integTest/scala/com/linkedin/photon/ml/SparkSessionConfigurationTest.scala, photon-api/src/integTest/scala/com/linkedin/photon/ml/function/DistributedObjectiveFunctionIntegTest.scala, photon-api/src/integTest/scala/com/linkedin/photon/ml/normalization/NormalizationContextIntegTest.scala, photon-api/src/integTest/scala/com/linkedin/photon/ml/optimization/DistributedOptimizationProblemIntegTest.scala, photon-api/src/integTest/scala/com/linkedin/photon/ml/supervised/BaseGLMIntegTest.scala, photon-api/src/main/scala/com/linkedin/photon/ml/ModelTraining.scala, photon-api/src/main/scala/com/linkedin/photon/ml/SparkSessionConfiguration.scala, photon-api/src/main/scala/com/linkedin/photon/ml/estimators/GameEstimator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/function/DistributedObjectiveFunction.scala, photon-api/src/main/scala/com/linkedin/photon/ml/function/glm/DistributedGLMLossFunction.scala, photon-api/src/main/scala/com/linkedin/photon/ml/function/svm/DistributedSmoothedHingeLossFunction.scala, photon-api/src/main/scala/com/linkedin/photon/ml/util/GameTestUtils.scala, photon-api/src/test/scala/com/linkedin/photon/ml/function/DistributedObjectiveFunctionTest.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriverIntegTest.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/data/avro/AvroDataReaderIntegTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/Driver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/GameScoringDriver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/avro/AvroDataReader.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/avro/NameAndTermFeatureBagsDriver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/index/FeatureIndexingDriver.scala, photon-lib/src/integTest/scala/com/linkedin/photon/ml/stat/BasicStatisticalSummaryIntegTest.scala
- Replace SQLContext with SparkSession
- Replace SparkContextConfiguration with SparkSessionConfiguration
- Remove a few cases where SparkContext explictly passed around
=> Minor replacement of SparkContext with SparkSession

photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/SliceSampler.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/estimators/GaussianProcessEstimator.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/estimators/kernels/Kernel.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/estimators/kernels/Matern52.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/estimators/kernels/RBF.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/estimators/kernels/StationaryKernel.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/search/GaussianProcessSearch.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/SliceSamplerTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/estimators/GaussianProcessEstimatorTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/estimators/GaussianProcessModelTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/estimators/kernels/Matern52Test.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/estimators/kernels/RBFTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/estimators/kernels/StationaryKernelTest.scala
For simplicity, the initial implementation of the Bayesian hyperparameter tuning module assumed a noiseless target function, and a covariance amplitude of 1.0. This commit adds the capability to learn noisy target functions and covariance amplitude from the observations.
For background on the Bayesian hyperparamter tuning module, see:
[https://docs.google.com/document/d/158Kjt4mbZrXWYFpo-ZElZ7ZU5ug8ZU5FQmap4YIVeT0](https://docs.google.com/document/d/158Kjt4mbZrXWYFpo-ZElZ7ZU5ug8ZU5FQmap4YIVeT0)
=> Add amplitude and noise to the hyperparamater tuning model

photon-api/src/integTest/scala/com/linkedin/photon/ml/optimization/DistributedOptimizationProblemIntegTest.scala, photon-api/src/main/scala/com/linkedin/photon/ml/function/glm/DistributedGLMLossFunction.scala, photon-api/src/main/scala/com/linkedin/photon/ml/function/glm/SingleNodeGLMLossFunction.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/DistributedOptimizationProblem.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/SingleNodeOptimizationProblem.scala, photon-lib/src/integTest/scala/com/linkedin/photon/ml/optimization/IntegTestObjective.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/function/L2Regularization.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/function/TwiceDiffFunction.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/function/glm/HessianMatrixAggregator.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/estimators/GaussianProcessModel.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/estimators/kernels/StationaryKernel.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/util/Linalg.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/optimization/TestObjective.scala
Here we mean variance in the sense of the posterior model distribution. We approximate the model variance by inverting the final Hessian matrix. This replaces the approximation that used just the Hessian diagonal, because it introduced too much error. See:
https://docs.google.com/document/d/1MAAeSIefs66q0tM2dXu-sNBtBlzUzVCVO7KmhOwCtmQ/edit?usp=sharing
=> Add computation of the full Hessian matrix for computing variance

photon-api/src/main/scala/com/linkedin/photon/ml/data/GameConverters.scala, photon-api/src/main/scala/com/linkedin/photon/ml/estimators/GameEstimator.scala
Generating unique ids is much less expensive since it doesn't trigger a job, and we don't need these ids to be sequential.
Also, guard the evaluation of expensive debugging information with a condition that checks whether we're actually in debug log level.
=> Use zipWithUniqueId instead of zipWithIndex

photon-api/src/main/scala/com/linkedin/photon/ml/data/GameConverters.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/InputColumnsNames.scala, photon-api/src/test/scala/com/linkedin/photon/ml/data/InputColumnsNamesTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/io/scopt/ScoptParserHelpers.scala, photon-client/src/test/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriverTest.scala, photon-client/src/test/scala/com/linkedin/photon/ml/io/scopt/ScoptParserHelpersTest.scala, photon-client/src/test/scala/com/linkedin/photon/ml/io/scopt/game/ScoptGameScoringParametersParserTest.scala, photon-client/src/test/scala/com/linkedin/photon/ml/io/scopt/game/ScoptGameTrainingParametersParserTest.scala
- Multiple columns in `InputColumnNames` could have the same name
- Columns used for grouping of random effects could have the same names as columns in `InputColumnNames`
=> Fix bug which allowed one column to be read for multiple purposes

photon-api/src/integTest/scala/com/linkedin/photon/ml/data/RandomEffectDataSetIntegTest.scala, photon-api/src/integTest/scala/com/linkedin/photon/ml/estimators/GameEstimatorIntegTest.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/CoordinateDataConfiguration.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/RandomEffectDataSet.scala, photon-api/src/main/scala/com/linkedin/photon/ml/estimators/GameEstimator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/model/RandomEffectModel.scala, photon-api/src/test/scala/com/linkedin/photon/ml/data/CoordinateDataConfigurationTest.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriverIntegTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/io/scopt/ScoptParserHelpers.scala, photon-client/src/main/scala/com/linkedin/photon/ml/io/scopt/game/ScoptGameTrainingParametersParser.scala, photon-client/src/test/scala/com/linkedin/photon/ml/io/scopt/ScoptParserHelpersTest.scala, photon-client/src/test/scala/com/linkedin/photon/ml/io/scopt/game/ScoptGameTrainingParametersParserTest.scala
- Add a lower bound for active data; any entity which does not have more data samples than the threshold will not have a random effect model trained
- Added option to ignore the threshold during warm-start when training models for random effect IDs that do not have an existing model
- Added/modified unit tests for new parameter
- Added integration test for new functionality in RandomEffectDataSet
=> Add new threshold parameter for training random effects

photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/criteria/ExpectedImprovement.scala
Add parentheses in the formula to compute EI. In breeze vector element-wise product operator :* has the lower operator priority than the elementwise addition +. Parentheses are needed.
=> Fix the bug to compute EI

photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/criteria/ConfidenceBound.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/criteria/ExpectedImprovement.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/estimators/PredictionTransformation.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/search/GaussianProcessSearch.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/search/RandomSearch.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/criteria/ConfidenceBoundTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/criteria/ExpectedImprovementTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/estimators/GaussianProcessModelTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/search/GaussianProcessSearchTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/search/RandomSearchTest.scala
@joshvfleming @basukinjal @yunboouyang
Tests are done for using EI and CB as prediction transformation to maximize and minimize normal distribution PDF. Other than the title literally, this PR also includes a change which reduce the time of unit tests.
=> Fix a bug in using expected improvement to predict minimization problems

photon-api/src/main/scala/com/linkedin/photon/ml/hyperparameter/tuner/AtlasTuner.scala, photon-api/src/main/scala/com/linkedin/photon/ml/hyperparameter/tuner/DummyTuner.scala, photon-api/src/main/scala/com/linkedin/photon/ml/hyperparameter/tuner/HyperparameterTuner.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/estimators/GameEstimatorEvaluationFunction.scala, photon-client/src/test/scala/com/linkedin/photon/ml/estimators/GameEstimatorEvaluationFunctionTest.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/criteria/ConfidenceBound.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/criteria/ExpectedImprovement.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/search/GaussianProcessSearch.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/criteria/ConfidenceBoundTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/criteria/ExpectedImprovementTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/search/GaussianProcessSearchTest.scala
Hi @joshvfleming @basukinjal, 
I didn't let the `GaussianProcessSearch` do minimization and let the `EvaluationFunction` handle flipping the sign based on two reasons:
1. `GaussianProcessSearch` will know that the problem is a min or max anyway because it will select the best eval of the prior data from past data sets, which all contain positive evals.
2. `findWithPriors` needs to know that the problem is a min or max to decide whether to flip the result for the output.
So I just keep the `EvaluationFunction` unchanged. Do you think it is a good way to implement? Thanks.
=> Decouple hyper-parameter autotuning from evaluator

photon-api/src/main/scala/com/linkedin/photon/ml/hyperparameter/tuner/AtlasTuner.scala, photon-api/src/main/scala/com/linkedin/photon/ml/hyperparameter/tuner/DummyTuner.scala, photon-api/src/main/scala/com/linkedin/photon/ml/hyperparameter/tuner/HyperparameterTuner.scala, photon-api/src/main/scala/com/linkedin/photon/ml/hyperparameter/tuner/HyperparameterTunerFactory.scala
@joshvfleming @basukinjal @ashelkovnykov Since atlas-ml is created now, we use atlas-ml for hyper-parameter-tuning.
=> Switch to atlas-ml for hyper-parameter tuning

photon-api/src/test/scala/com/linkedin/photon/ml/util/GameTestUtils.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/data/DataValidatorsIntegTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/DataValidators.scala, photon-client/src/test/scala/com/linkedin/photon/ml/data/avro/AvroDataWriterTest.scala, photon-lib/src/integTest/scala/com/linkedin/photon/ml/stat/FeatureDataStatisticsIntegTest.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/Types.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/data/LabeledPoint.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/util/VectorUtils.scala
All references to mllib.linalg.Vectors are contained within VectorUtils.scala.
Ideally we should remove all references to mllib.linalg.Vectors, but there are
certain cases where mllib.linalg.Vectors are still needed and cannot be refactored easily.
=> Remove reference to mllib.linalg.Vectors

photon-client/src/integTest/scala/com/linkedin/photon/ml/data/DataValidatorsIntegTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/DataValidators.scala, photon-client/src/test/scala/com/linkedin/photon/ml/data/DataValidatorsTest.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/util/VectorUtils.scala
- Add support for all numeric types (not just `Double`)
- Support Spark `DenseVector`
- Fix bug that would cause OOM failure when generating error message
=> Fix 3 bugs found in DataValidators

photon-api/src/integTest/scala/com/linkedin/photon/ml/function/glm/DistributedGLMLossFunctionIntegTest.scala, photon-api/src/integTest/scala/com/linkedin/photon/ml/function/svm/DistributedSmoothedHingeLossFunctionIntegTest.scala, photon-api/src/main/scala/com/linkedin/photon/ml/function/glm/DistributedGLMLossFunction.scala, photon-api/src/main/scala/com/linkedin/photon/ml/function/glm/SingleNodeGLMLossFunction.scala, photon-api/src/main/scala/com/linkedin/photon/ml/function/svm/DistributedSmoothedHingeLossFunction.scala, photon-api/src/main/scala/com/linkedin/photon/ml/function/svm/SingleNodeSmoothedHingeLossFunction.scala, photon-api/src/test/scala/com/linkedin/photon/ml/function/glm/SingleNodeGLMLossFunctionTest.scala, photon-api/src/test/scala/com/linkedin/photon/ml/function/svm/SingleNodeSmoothedHingeLossFunctionTest.scala
This PR fixes the bug of elastic net regularization. Unit tests are added for GLM and smoothed hinge loss functions on a single node and distributed nodes.
=> Fix elastic net bug

photon-api/src/integTest/scala/com/linkedin/photon/ml/estimators/GameEstimatorIntegTest.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/LocalDataset.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/RandomEffectDataset.scala, photon-api/src/main/scala/com/linkedin/photon/ml/projector/IndexMapProjectorRDD.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/util/VectorUtils.scala
`numActiveFeatures` should only be used in one place, and is expensive to compute, so remove it as a member of `LocalDataset`.
`VectorUtils.getActiveIndices` uses immutable `Set` objects which cause too much latency when dealing with large random effects due to inefficient Scala construction algorithm - replace with mutable `Set` objects.
=> Improve RandomEffectDataset Performance

photon-api/src/integTest/scala/com/linkedin/photon/ml/projector/IndexMapProjectorRDDIntegTest.scala, photon-api/src/main/scala/com/linkedin/photon/ml/algorithm/RandomEffectCoordinate.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/CoordinateDataConfiguration.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/RandomEffectDataset.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/RandomEffectDatasetInProjectedSpace.scala, photon-api/src/main/scala/com/linkedin/photon/ml/estimators/GameEstimator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/projector/IndexMapProjectorRDD.scala, photon-api/src/main/scala/com/linkedin/photon/ml/projector/ProjectionMatrixBroadcast.scala, photon-api/src/test/scala/com/linkedin/photon/ml/data/CoordinateDataConfigurationTest.scala, photon-api/src/test/scala/com/linkedin/photon/ml/util/GameTestUtils.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriverIntegTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/io/scopt/ScoptParserHelpers.scala, photon-client/src/test/scala/com/linkedin/photon/ml/data/avro/NameAndTermFeatureBagsDriverTest.scala, photon-client/src/test/scala/com/linkedin/photon/ml/index/FeatureIndexingDriverTest.scala, photon-client/src/test/scala/com/linkedin/photon/ml/io/scopt/ScoptParserHelpersTest.scala, photon-client/src/test/scala/com/linkedin/photon/ml/io/scopt/game/ScoptGameTrainingParametersParserTest.scala
The reasoning is that it is a rarely-used tuning parameter which requires rather specific knowledge of the implementation of Photon ML (i.e. the difference between "active" and "passive" data).
Maintaining this tuning parameter increases training time (the code for computing passive datasets is run regardless - but with the tuning parameter, the number of samples per entity now also need to be counted and filtered), reduces accuracy (since records for entities which do not break the bound threshold will not be scored), and introduces additional code complexity (lots of `Option` objects).
=> Remove the lower bound on passive dataset size as a tuning parameter

photon-api/src/main/scala/com/linkedin/photon/ml/data/FixedEffectDataset.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/RandomEffectDataset.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/RandomEffectDatasetInProjectedSpace.scala, photon-api/src/main/scala/com/linkedin/photon/ml/model/RandomEffectModel.scala, photon-api/src/main/scala/com/linkedin/photon/ml/model/RandomEffectModelInProjectedSpace.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/RandomEffectOptimizationTracker.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/game/RandomEffectOptimizationProblem.scala, photon-api/src/main/scala/com/linkedin/photon/ml/projector/IndexMapProjectorRDD.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/data/scoring/DataScores.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/evaluation/EvaluationSuite.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/spark/RDDLike.scala
Change made in preparation for projection refactor (it was not working correctly anyway). After persistence refactor, this function will likely be completely removed.
=> Remove 'materializeOnce' function from RDDLike trait 

photon-api/src/integTest/scala/com/linkedin/photon/ml/evaluation/MultiEvaluatorIntegTest.scala, photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/AreaUnderPRCurveEvaluator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/AreaUnderROCCurveEvaluator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/AreaUnderROCCurveLocalEvaluator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/LogisticLossEvaluator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/PoissonLossEvaluator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/PrecisionAtKLocalEvaluator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/RMSEEvaluator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/SmoothedHingeLossEvaluator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/SquaredLossEvaluator.scala, photon-api/src/test/scala/com/linkedin/photon/ml/evaluation/PrecisionAtKLocalEvaluatorTest.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/evaluation/Evaluator.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/evaluation/LocalEvaluator.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/evaluation/MultiEvaluator.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/evaluation/EvaluationSuiteTest.scala
- Change permissions of Evaluator.evaluate and all derived classes to public
- Add PrecisionAtKLocalEvaluator unit tests
=> Loosen permissions on Evaluator.evaluate method

photon-api/src/main/scala/com/linkedin/photon/ml/model/RandomEffectModel.scala, photon-api/src/main/scala/com/linkedin/photon/ml/model/RandomEffectModelInProjectedSpace.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/data/avro/ModelProcessingUtilsIntegTest.scala
This change is made in preparation for the projection refactor, after which `RandomEffectModelInProjectedSpace` will no longer exist and the number of calls to `determineModelType` should no longer cause noticeable performance impact (allowing us to simplify the code)
=> Minor refactor to DatumScoringModel modelType

photon-client/src/main/scala/com/linkedin/photon/ml/util/IOUtils.scala
Fix output stream writer to UTF-8 format to solve generating inconsistent feature list issue when running NameAndTermFeatureBagsDriver in photon-client
=> Fix output stream writer to UTF-8 format

photon-api/src/main/scala/com/linkedin/photon/ml/estimators/GameEstimator.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriver.scala, photon-client/src/test/scala/com/linkedin/photon/ml/cli/game/GameDriverTest.scala
This PR solves the Spark lineage issue by disabling warm start for autotuning. Without this change, GAME training jobs with multiple number of iterations for hyperparameter search failed because of the limitation of Spark lineage. After applying the change, tests for grid search and autotuning ran stable.
=> Solve the Spark lineage problem by disabling warm start for autotuning

.travis.yml
For some reason, using 'xenial' has started causing test failures. This is a known issue:
https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/5
https://travis-ci.community/t/install-jdk-sh-failing-for-openjdk9-and-10/3998/27
=> Lock Travis CI to 'trusty' distribution

photon-api/src/integTest/scala/com/linkedin/photon/ml/algorithm/CoordinateFactoryIntegTest.scala, photon-api/src/integTest/scala/com/linkedin/photon/ml/supervised/BaseGLMIntegTest.scala, photon-api/src/main/scala/com/linkedin/photon/ml/algorithm/CoordinateFactory.scala, photon-api/src/main/scala/com/linkedin/photon/ml/algorithm/RandomEffectCoordinate.scala, photon-api/src/main/scala/com/linkedin/photon/ml/estimators/GameEstimator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/function/ObjectiveFunctionHelper.scala, photon-api/src/main/scala/com/linkedin/photon/ml/function/glm/DistributedGLMLossFunction.scala, photon-api/src/main/scala/com/linkedin/photon/ml/function/glm/GLMLossFunction.scala, photon-api/src/main/scala/com/linkedin/photon/ml/function/glm/SingleNodeGLMLossFunction.scala, photon-api/src/main/scala/com/linkedin/photon/ml/function/svm/DistributedSmoothedHingeLossFunction.scala, photon-api/src/main/scala/com/linkedin/photon/ml/function/svm/SingleNodeSmoothedHingeLossFunction.scala, photon-api/src/main/scala/com/linkedin/photon/ml/function/svm/SmoothedHingeLossFunction.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/game/RandomEffectOptimizationProblem.scala, photon-api/src/test/scala/com/linkedin/photon/ml/function/DistributedObjectiveFunctionTest.scala, photon-api/src/test/scala/com/linkedin/photon/ml/function/ObjectiveFunctionHelperTest.scala, photon-api/src/test/scala/com/linkedin/photon/ml/function/glm/GLMLossFunctionTest.scala, photon-api/src/test/scala/com/linkedin/photon/ml/function/svm/SmoothedHingeLossFunctionTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/util/IOUtils.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/function/L2Regularization.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/function/L2RegularizationTest.scala
This is continuation of the work started by @biyan-linkedin in PR #439. Thank you for your work Bill!
Previously, Photon would regularize the entire coefficient vector, including the intercept coefficient if one was present. One of our users had this to say:
```
Penalizing intercept makes the behavior of L2 regularization depends
on the pos/neg ratio, and often leads to hard-to-interpret intercept.
Especially when we have a lot of training data and most of the features
are extremely sparse.
```
=> Disable L2 Regularization on Intercept

photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/SquaredLossEvaluator.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriverIntegTest.scala
Changes:
1. Add correct calculation of squared loss, which will be used to compute Rooted Mean Squared Error (RMSE) by taking average and squared root. 
2. Multiply the error threshold by sqrt(2) since RMSE calculation has been changed.
=> Fix a bug in calculating RMSE off by sqrt(2)

photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriver.scala
Fix a hyperparameter tuning dimension calculation bug. 
1. The dimension should be equal to the number of lambdas (magnitude) and alphas (mixing weights). 
2. Right now the dimension is equal to the number of coordinates.
=> Fix a hyperparameter tuning dimension mismatch bug

photon-lib/src/main/scala/com/linkedin/photon/ml/model/Coefficients.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/model/CoefficientsTest.scala
`Coefficients` case class requires means and variances should be of the same type (both are `SparseVector` or `DenseVector`). However this requirement is not needed.
=> Remove mean and variance type consistency check

photon-api/src/integTest/scala/com/linkedin/photon/ml/data/RandomEffectDatasetIntegTest.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/RandomEffectDataset.scala, photon-api/src/main/scala/com/linkedin/photon/ml/estimators/GameEstimator.scala
When constructing subspace linear projectors, prior model's active indices should be union with data's active indices, otherwise some of prior model's coefficients will be dropped in the training process. An union step is added in this PR.
=> Construct projectors incorporating with prior models

photon-api/src/integTest/scala/com/linkedin/photon/ml/data/RandomEffectDatasetIntegTest.scala, photon-api/src/main/scala/com/linkedin/photon/ml/algorithm/RandomEffectCoordinate.scala, photon-api/src/main/scala/com/linkedin/photon/ml/algorithm/RandomEffectModelCoordinate.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/RandomEffectDataset.scala
This PR merges conflicts for https://github.com/linkedin/photon-ml/pull/453 by changing `generateLinearSubspaceProjectors` function in `RandomEffectDataset.scala`
=> Fix bug which caused all per-entity data sent to a single partitioner before sampling

photon-api/src/integTest/scala/com/linkedin/photon/ml/normalization/NormalizationContextIntegTest.scala, photon-api/src/integTest/scala/com/linkedin/photon/ml/supervised/BaseGLMIntegTest.scala, photon-api/src/main/scala/com/linkedin/photon/ml/ModelTraining.scala, photon-api/src/main/scala/com/linkedin/photon/ml/algorithm/FixedEffectCoordinate.scala, photon-api/src/main/scala/com/linkedin/photon/ml/algorithm/RandomEffectCoordinate.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/DistributedOptimizationProblem.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/GeneralizedLinearOptimizationProblem.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/SingleNodeOptimizationProblem.scala, photon-api/src/test/scala/com/linkedin/photon/ml/algorithm/FixedEffectCoordinateTest.scala, photon-api/src/test/scala/com/linkedin/photon/ml/optimization/DistributedOptimizationProblemTest.scala, photon-api/src/test/scala/com/linkedin/photon/ml/optimization/GeneralizedLinearOptimizationProblemTest.scala, photon-api/src/test/scala/com/linkedin/photon/ml/optimization/SingleNodeOptimizationProblemTest.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/optimization/Optimizer.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/optimization/LBFGSBTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/optimization/LBFGSTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/optimization/OWLQNTest.scala
Update optimization problems to return updated model and states tracker
all together to avoid NPEs. 
Compared with https://github.com/linkedin/photon-ml/pull/464, this PR changed line 257 of RandomEffectCoordinate.scala to unify different cases.
=> Refactor optimization states tracker

photon-api/src/main/scala/com/linkedin/photon/ml/function/glm/GLMLossFunction.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/DistributedOptimizationProblem.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/GeneralizedLinearOptimizationProblem.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/SingleNodeOptimizationProblem.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/function/PriorDistribution.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/normalization/NormalizationContext.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/optimization/Optimizer.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/function/PriorDistributionTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/normalization/NormalizationContextTest.scala
Had a minor refactor of feature normalization related code. Changes are:
1. Fixed a bug in calculating variance when feature normalization is enabled. Previous variance calculation function `createModel` was wrong because means and variance cannot share the same transformation. The correct way of calculating variance when feature normalization is enabled is: first transform the means back to the original space, and then call `computeVariances` function. 
2. Added `normalizationContext` in `PriorDistribution.scala` to enable mean and variance normalization in incremental learning.
=> Minor Feature Normalization Refactor

CHANGELOG.md, jcenter/bintray.gradle, photon-api/src/main/scala/com/linkedin/photon/ml/estimators/GameEstimator.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/io/scopt/game/ScoptGameTrainingParametersParser.scala, photon-client/src/main/scala/com/linkedin/photon/ml/util/IOUtils.scala, photon-client/src/test/scala/com/linkedin/photon/ml/io/scopt/game/ScoptGameTrainingParametersParserTest.scala, photon-lib/src/integTest/scala/com/linkedin/photon/ml/algorithm/CoordinateDescentIntegTest.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/algorithm/CoordinateDescent.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/evaluation/EvaluationResults.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/evaluation/EvaluationSuite.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/evaluation/MultiEvaluator.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/algorithm/CoordinateDescentTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/evaluation/EvaluationResultsTest.scala, release-bintray.gradle
When the number of random effect entities is small, e.g. in the cohort-based models, users would like to check the evaluations on each group (data grouped by member id, job id, cohort id etc) and analyze the importance of each group to overall evaluation. This PR aims to output the per group evaluation in separate output files.
=> Add per group evaluation output

photon-client/src/main/scala/com/linkedin/photon/ml/util/IOUtils.scala, release-bintray.gradle
Change per-group evaluation output data frame `coalesce` to `repartition` to speed up the I/O.
=> Optimize per-group evaluation I/O
