linkedin/photon-ml

photon-ml/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/DriverGameIntegTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/model/ModelProcessingUtils.scala
This adds basic checking that the trained GAME models produce scores
with validation error below a predefined threshold.
=> Add model score evaluation to GAME driver integration tests

photon-ml/src/integTest/scala/com/linkedin/photon/ml/DriverIntegTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/ModelSelection.scala
Part of the effort described in issue #53.
The main changes come from fixing the "Method is longer than 50 lines" warning by extracting out some logically independent pieces of code and re-organize the function layout.
No logically changes made to Driver.
=> Fix Scala style warnings in com.linkedin.photon.ml.Driver

photon-ml/src/main/scala/com/linkedin/photon/ml/util/PhotonLogger.scala
This PR address the issue discussed in #62.
=> Change the scope of some fields in object PhotonLogger

build.gradle
I think this may be the cause for our occasional deployment issue. See me for more details.
=> Modify repository declarations for root Gradle buildscript

photon-avro-schemas/src/main/avro/LatentFactorAvro.avsc, photon-ml/src/integTest/scala/com/linkedin/photon/ml/avro.model/ModelProcessingUtilsTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/model/MatrixFactorizationModelTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/AvroUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/data/DataProcessingUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/data/NameAndTermFeatureSetContainer.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/model/ModelProcessingUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/model/MatrixFactorizationModel.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/avro/AvroUtilsTest.scala, photon-test/src/main/scala/com/linkedin/photon/ml/test/TestTemplateWithTmpDir.scala
This PR has three commits:
1. Fix the bug when creating the temporary dir
2. Change the function name in Avro I/O util to make it more consistent
3. Addresses issue #56 and provides Avro I/O util functions for the matrix factorization model.
=> Adding Avro I/O util functions for matrix factorization model

photon-ml/build.gradle
This is needed for some joda time functions
=> Add joda convert dependency

photon-ml/src/main/scala/com/linkedin/photon/ml/model/Coefficients.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/model/FixedEffectModel.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/model/MatrixFactorizationModel.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/model/RandomEffectModel.scala
Part of #53.
Most of the changes come with the warning that equals and hashCode should be implemented together.
=> Fix some of the scalaStyle warning issues in the model package.

photon-ml/src/main/scala/com/linkedin/photon/ml/avro/data/NameAndTermFeatureSetContainer.scala
This change was missed in the changes for PR:
https://github.com/linkedin/photon-ml/pull/79
=> Add relative date ranges to NameAndTermFeatureSetContainer

photon-ml/src/integTest/scala/com/linkedin/photon/ml/BootstrapTrainingIntegTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/DriverIntegTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/normalization/NormalizationIntegTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/supervised/BaseGLMIntegTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/BootstrapTraining.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/Evaluation.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/ModelTraining.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/model/ModelProcessingUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/diagnostics/bootstrap/BootstrapTrainingDiagnostic.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/io/GLMSuite.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/normalization/NormalizationContext.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/supervised/classification/LogisticRegressionAlgorithm.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/supervised/classification/LogisticRegressionModel.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/supervised/classification/SmoothedHingeLossLinearSVMAlgorithm.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/supervised/classification/SmoothedHingeLossLinearSVMModel.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/supervised/model/GeneralizedLinearAlgorithm.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/supervised/model/GeneralizedLinearModel.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/supervised/regression/LinearRegressionAlgorithm.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/supervised/regression/LinearRegressionModel.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/supervised/regression/PoissonRegressionAlgorithm.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/supervised/regression/PoissonRegressionModel.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/supervised/regression/Regression.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/BootstrapTrainingTest.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/diagnostics/featureimportance/FeatureImportanceDiagnosticTest.scala
Addresses issue #81.
Also some Scala style fixes in files that were modified.
=> Remove legacy intercept code

photon-ml/src/integTest/scala/com/linkedin/photon/ml/avro.model/ModelProcessingUtilsTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/DriverGameIntegTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/model/FixedEffectModelTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/model/GAMEModelTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/algorithm/CoordinateDescent.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/model/ModelProcessingUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/model/GAMEModel.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/model/MatrixFactorizationModel.scala
Add a new data structure ```GAMEModel``` to represent the GAME model, and some tests.
See issue #94 for more details.
=> Add GAMEModel to represent the GAME model

photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Params.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Params.scala
1. Adding the format example for ```featureShardIdToInterceptMap```.
2. Reformat the code.
=> Minor doc fix for PR#100

README.md, photon-ml/src/main/scala/com/linkedin/photon/ml/BootstrapTraining.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/diagnostics/hl/AbstractPredictedProbabilityVersusObservedFrequencyBinner.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/diagnostics/hl/FixedPredictedProbabilityVersusObservedFrequencyBinner.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/diagnostics/hl/PredictedProbabilityVersusObservedFrequencyHistogramBin.scala
This addresses issue https://github.com/linkedin/photon-ml/issues/76
I've tested this flow on an OS X machine and a Linux machine (Ubuntu 16.04).
=> Add training walkthough on public dataset to README

photon-ml/src/main/scala/com/linkedin/photon/ml/util/PhotonLogger.scala
Currently PhotonLogger is maintaining a remote output stream with HDFS directly,
the connection could be easily interrupted due to cluster/network instability if the job
is running for a long time. e.g. hours. In my env, this could happen occasionally. Though not a bit issue, but when it happens that means a heavy job just failed and I would waste hours waiting.
Therefore, I'm suggesting change the the behavior by firstly writing the logs onto a local tmp file and then finally copy it from local to HDFS when the logger is closed.
=> Improve PhotonLogger stability when jobs are running for hours

photon-ml/src/integTest/scala/com/linkedin/photon/ml/DriverIntegTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/MockDriver.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/cli/game/scoring/DriverTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/DriverTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/util/IOUtilsIntegTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/OptionNames.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/Params.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/PhotonMLCmdLineParser.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/data/NameAndTermFeatureSetContainer.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Params.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Params.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/data/FixedEffectDataConfiguration.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/data/RandomEffectDataConfiguration.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/game/GLMOptimizationConfiguration.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/game/MFOptimizationConfiguration.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/IOUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/PhotonLogger.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/cli/game/training/ParamsTest.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/data/FixedEffectDataConfigurationTest.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/data/RandomEffectDataConfigurationTest.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/optimization/game/GLMOptimizationConfigurationTest.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/optimization/game/MFOptimizationConfigurationTest.scala
This PR addresses issue #111.
Looks simple, but the amount of work required for this PR is more than I anticipated, as it involves a few changes to some legacy code and missing tests.
I tried to not touch the code that is not directly related to issue #111, but still, this PR has to involve quite a few code refactoring. But I tried to split this PR into a few logical commits, please take a look.
Both unit and integration tests are added to cover the changes made.
=> Add input argument to delete output directory if exists

photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Params.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/cli/game/training/ParamsTest.scala
More details can be find in issue #135.
Unit test also added to cover the bug.
=> Fix the bug where colon is replaced by underscore.

photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Params.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/cli/game/training/ParamsTest.scala
This PR addresses the bug reported in issue #137.
@joshvfleming @timyitong
=> Making updating-sequence a required parameter.

photon-ml/src/integTest/scala/com/linkedin/photon/ml/cli/game/scoring/DriverTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Params.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/cli/game/scoring/ParamsTest.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/cli/game/training/ParamsTest.scala, photon-test/src/main/scala/com/linkedin/photon/ml/test/CommonTestUtils.scala
See issue #142 for more details.
=> Change "random-effect-id-set" in GAME's scoring Params to a non-required parameter

photon-ml/src/integTest/scala/com/linkedin/photon/ml/cli/game/scoring/DriverTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Params.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/EvaluatorType.scala
See issue #146 for more details.
Tests done: integration tests.
=> Evaluate the computed scores within GAME's scoring driver.

photon-ml/src/main/scala/com/linkedin/photon/ml/avro/AvroUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/data/NameAndTermFeatureSetContainer.scala
=> Fix NameAndTermFeatureSetContainer.main on very large input data

photon-ml/src/main/scala/com/linkedin/photon/ml/algorithm/CoordinateDescent.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/Timer.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/util/TimerTest.scala
This removes some repetitive timing code from the critical path
=> Add Timer class to improve code readability

photon-ml/src/main/scala/com/linkedin/photon/ml/algorithm/FactoredRandomEffectCoordinate.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/GeneralizedLinearOptimizationProblem.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/algorithm/FixedEffectCoordinateTest.scala
Minor: ```GeneralizedLinearOptimizationProblem``` shouldn't extend the ```DownSampler``` trait.
=> Minor refactoring for downsamplers in GLM optimization problem.

photon-ml/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/DriverTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala
We weren't stopping the timer here if no validating dir was
specified. Also, add test to validate this code path.
=> Fix bug where Timer is never stopped

photon-ml/src/main/scala/com/linkedin/photon/ml/avro/data/DataProcessingUtils.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/avro/data/DataProcessingUtilsTest.scala
See discussion and comments on #158 for more details.
=> Fix Scala style issues and remaining issues for PR158

photon-ml/src/integTest/scala/com/linkedin/photon/ml/cli/game/scoring/DriverTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/evaluation/PrecisionAtKEvaluatorTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/AreaUnderROCCurveEvaluator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/EvaluatorType.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/PrecisionAtKEvaluator.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/function/PointwiseLossFunctionTest.scala
Part of the effort to address issue #151.
=> Add precision@K evaluator with tests.

README.md
=> Link GLMix paper to README.md and add more explanations to GAME.

photon-ml/src/main/scala/com/linkedin/photon/ml/data/GameConverters.scala
This is a follow-on to PR #179
=> Use vector converter instead of ad-libing

photon-ml/src/main/scala/com/linkedin/photon/ml/RDDLike.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/algorithm/CoordinateDescent.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/data/KeyValueScore.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/algorithm/CoordinateDescentTest.scala
Let me know what you think. I've added a simple unit test that passes.
=> Fix for issue #181: track best model in CoordinateDescent

photon-ml/src/integTest/scala/com/linkedin/photon/ml/avro/ModelProcessingUtilsTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/DriverTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/model/FixedEffectModelTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/model/MatrixFactorizationModelTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/normalization/NormalizationContextIntegTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/algorithm/CoordinateDescent.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/algorithm/FixedEffectCoordinate.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/AvroUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/model/ModelProcessingUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/model/Coefficients.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/model/FixedEffectModel.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/model/GAMEModel.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/model/RandomEffectModel.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/supervised/model/GeneralizedLinearModel.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/DefaultIndexMap.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/DefaultIndexMapLoader.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/IndexMapLoader.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/Utils.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/model/CoefficientsTest.scala
This is for model conversion - I need an API to load Game models from HDFS without having a feature index. In that case, the feature index is generated on the fly when the model is loaded.
=> Adding generation of default index maps when reading Game model

photon-ml/src/integTest/scala/com/linkedin/photon/ml/avro/ModelProcessingUtilsTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/RDDLike.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/model/ModelProcessingUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/io/GLMSuite.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/model/RandomEffectModel.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/IndexMapLoader.scala
This will be required to write a model converter.
=> Adding extractGameModelFeatures and unit tests

photon-ml/src/main/scala/com/linkedin/photon/ml/avro/AvroUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/model/ModelProcessingUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/DefaultIndexMap.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/DefaultIndexMapLoader.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/PalDBIndexMap.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/Utils.scala
Minor style issues I noticed in previous commits but did not mark in time. If you disagree with them, please let me know. We can reach a consensus and add them to the Photon style guide we're slowly working towards (if they do not fall under Scala/Spark style documents already).
=> Minor Scala style changes

photon-ml/build.gradle, photon-ml/src/integTest/scala/com/linkedin/photon/ml/avro/ModelProcessingUtilsTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/util/IOUtilsIntegTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/model/ModelProcessingUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/IOUtils.scala, photon-ml/src/test/resources/log4j.properties, photon-ml/src/test/scala/com/linkedin/photon/ml/util/IOUtilsTest.scala
=> Adding IOUtils.safePrintToStream

photon-ml/src/integTest/scala/com/linkedin/photon/ml/optimization/RandomEffectOptimizationTrackerTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/Evaluation.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/ModelSelection.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/ModelTraining.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/data/DataValidators.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/data/GameConverters.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/diagnostics/fitting/FittingDiagnostic.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/DistributedOptimizationProblem.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/GeneralizedLinearOptimizationProblem.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/OptimizationStatesTracker.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/Optimizer.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/SingleNodeOptimizationProblem.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/optimization/TRON.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/stat/BasicStatisticalSummary.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/ConvergenceReason.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/Logging.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/optimization/OptimizerTest.scala
These changes allow the code to build for Spark 2.*.
See also: https://github.com/linkedin/photon-ml/issues/189
=> Spark 2.* compatibility fixes

photon-ml/src/integTest/scala/com/linkedin/photon/ml/GameTestUtils.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/avro/ModelProcessingUtilsTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/DriverTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/estimators/GameEstimatorTest.scala, photon-ml/src/integTest/scala/com/linkedin/photon/ml/optimization/OptimizerIntegTest.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/algorithm/CoordinateDescent.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/avro/model/ModelProcessingUtils.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/GAMEDriver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/estimators/GameEstimator.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/estimators/GameParams.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/evaluation/Evaluator.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/algorithm/CoordinateDescentTest.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/estimators/GameParamsTest.scala, photon-ml/src/test/scala/com/linkedin/photon/ml/function/SingleNodeObjectiveFunctionTest.scala
This is an initial nudge in the direction of the new API. I've made this change mostly to enable hyperparameter optimization, and also to get the API ball rolling.
- Optimization logic moved from Driver to GameEstimator
- Tests updated to reflect code changes
- Some minor cleanup around the periphery
| Code | AUC | Time (m) |
| --- | --- | --- |
| Before #222 | 0.65435068 | 13.15227361 |
| After #222 | 0.65435068 | 12.27700118 |
No difference in coefficient stats.
=> Initial cut of moving Game code from Driver to GameEstimator

photon-ml/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/stat/BasicStatisticalSummary.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/stat/BasicStatistics.scala, photon-ml/src/main/scala/com/linkedin/photon/ml/util/Logging.scala
Minor cleanups, usually suggested by IDEA/Scala.
=> Minor cleanups

defaultEnvironment.gradle, photon-ml/build.gradle
Necessary to override package internally to LinkedIn.
=> Add modifier for avro-mapred package to defaultEnvironment.gradle

photon-ml/src/integTest/scala/com/linkedin/photon/ml/cli/game/scoring/DriverTest.scala
For some random seeds and different sequences of random value generation, this test would fail because all the labels for either queryId or documentId happened to be the same, which produces an AUC of NaN. The fix is to add static data that ensures that each item id has both positive and negative labels.
=> Fix bug where GAME scoring Driver test sometimes failed with NaN

build.gradle, photon-ml/src/main/scala/com/linkedin/photon/ml/projector/README.md
After discussion with Bee-Chung.
=> Adding documentation about random projections

.gitignore, build.gradle, photon-client/build.gradle, photon-client/src/main/scala/com/linkedin/photon/ml/ModelSelection.scala, photon-client/src/main/scala/com/linkedin/photon/ml/PhotonMLCmdLineParser.scala, photon-client/src/main/scala/com/linkedin/photon/ml/PhotonOptionNames.scala, photon-client/src/main/scala/com/linkedin/photon/ml/io/GLMSuite.scala, photon-client/src/main/scala/com/linkedin/photon/ml/util/Utils.scala, photon-client/src/test/scala/com/linkedin/photon/ml/io/GLMSuiteTest.scala, photon-diagnostics/src/main/scala/com/linkedin/photon/ml/Evaluation.scala, photon-diagnostics/src/main/scala/com/linkedin/photon/ml/diagnostics/bootstrap/BootstrapTrainingDiagnostic.scala, photon-diagnostics/src/main/scala/com/linkedin/photon/ml/diagnostics/reporting/RenderStrategy.scala, photon-diagnostics/src/test/scala/com/linkedin/photon/ml/diagnostics/reporting/RenderStrategyTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/optimization/OptimizationUtilsTest.scala, photon-test-utils/src/main/scala/com/linkedin/photon/ml/test/SparkTestUtils.scala
As per title. This shouldn't affect any functionality, I just removed several compile-time warnings, so that it is easier to see the real errors at once. 
Also includes various minor cleanups.
=> Removing several compile-time warnings

photon-api/src/main/scala/com/linkedin/photon/ml/util/DefaultIndexMap.scala, photon-api/src/main/scala/com/linkedin/photon/ml/util/DefaultIndexMapLoader.scala, photon-api/src/main/scala/com/linkedin/photon/ml/util/IndexMap.scala, photon-api/src/main/scala/com/linkedin/photon/ml/util/IndexMapBuilder.scala, photon-api/src/main/scala/com/linkedin/photon/ml/util/PalDBIndexMap.scala, photon-api/src/main/scala/com/linkedin/photon/ml/util/PalDBIndexMapBuilder.scala, photon-api/src/main/scala/com/linkedin/photon/ml/util/PalDBIndexMapLoader.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/data/AvroDataReaderTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/GAMEDriver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/io/InputFormatFactory.scala
Refactored PalDBIndexMapLoader to make initialization sequence more robust
Added comments for various index map related classes
Various minor cleanups
=> Feature index map cleanups

photon-client/src/integTest/scala/com/linkedin/photon/ml/avro/AvroIOUtilsTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/FeatureIndexingJob.scala, photon-client/src/main/scala/com/linkedin/photon/ml/avro/AvroIOUtils.scala, photon-client/src/main/scala/com/linkedin/photon/ml/avro/AvroUtils.scala, photon-client/src/main/scala/com/linkedin/photon/ml/avro/data/NameAndTermFeatureSetContainer.scala, photon-client/src/main/scala/com/linkedin/photon/ml/avro/data/ScoreProcessingUtils.scala, photon-client/src/main/scala/com/linkedin/photon/ml/avro/model/ModelProcessingUtils.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/AvroDataReader.scala, photon-client/src/main/scala/com/linkedin/photon/ml/io/GLMSuite.scala
Fixed Issue #33, simplifying readFromAvro between AvroUtils and AvroIOUtils
=> AvroUtils/AvroIOUtils simplification (issue #33)

photon-api/src/main/scala/com/linkedin/photon/ml/data/RandomEffectDataSetPartitioner.scala
Documenting the rationale behind the way we partition in Game.
=> More documentation about the RandomEffectDataSetPartitioner

photon-client/src/main/scala/com/linkedin/photon/ml/data/avro/AvroDataReader.scala, photon-client/src/test/scala/com/linkedin/photon/ml/data/avro/AvroDataReaderTest.scala
This change allows AvroDataReader to more gracefully handle situations where Avro union fields are specified with many numeric types, e.g. [INT, LONG, FLOAT, DOUBLE]. We introduce a concept of numeric precedence and use this simple rule to select the type.
=> Improve handling of nutty union types in AvroDataReader

build.gradle
We need this for LinkedIn internal reasons.
=> Bumping version of John Rengelman's shadow plugin to 1.2.4

photon-api/src/main/scala/com/linkedin/photon/ml/data/RandomEffectDataSet.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/DriverTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/DataReader.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/avro/AvroDataReader.scala, photon-client/src/main/scala/com/linkedin/photon/ml/estimators/GameEstimator.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/Types.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/util/Timed.scala
Small things that should be all good.
=> Comments, names and various small fixes or improvements.

photon-api/src/main/scala/com/linkedin/photon/ml/data/RandomEffectDataSetPartitioner.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/avro/AvroUtils.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/Types.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/optimization/Optimizer.scala
=> Small fixes

photon-api/src/main/scala/com/linkedin/photon/ml/estimators/GameEstimator.scala, photon-client/build.gradle, photon-client/src/main/scala/com/linkedin/photon/ml/HyperparameterTuningMode.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingParams.scala, photon-client/src/main/scala/com/linkedin/photon/ml/estimators/GameEstimatorEvaluationFunction.scala, photon-client/src/test/scala/com/linkedin/photon/ml/estimators/GameEstimatorEvaluationFunctionTest.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/EvaluationFunction.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/Linalg.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/SliceSampler.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/criteria/ConfidenceBound.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/criteria/ExpectedImprovement.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/estimators/GaussianProcessEstimator.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/estimators/GaussianProcessModel.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/estimators/PredictionTransformation.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/estimators/kernels/Kernel.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/estimators/kernels/Matern52.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/estimators/kernels/RBF.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/estimators/kernels/StationaryKernel.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/search/GaussianProcessSearch.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/search/RandomSearch.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/SliceSamplerTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/estimators/GaussianProcessEstimatorTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/estimators/GaussianProcessModelTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/estimators/kernels/Matern52Test.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/estimators/kernels/RBFTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/search/GaussianProcessSearchTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/search/RandomSearchTest.scala
This PR adds a hyperparameter tuning module. At present, there are two modes: random search, and Bayesian optimization. For full details, see the design note here:
https://docs.google.com/document/d/158Kjt4mbZrXWYFpo-ZElZ7ZU5ug8ZU5FQmap4YIVeT0/edit?usp=sharing
@ashelkovnykov @fastier-li Please review.
@XianXing I'd also appreciate any feedback from you on this, if and when you have time.
=> Initial commit of hyperparameter optimization

photon-api/src/main/scala/com/linkedin/photon/ml/optimization/OptimizerState.scala
https://github.com/linkedin/photon-ml/issues/290
=> [Issue 290] Inconsistency in OptimizerState between photon-api and photon-ml

photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingParams.scala
Doing this for backward performance compatibility.
=> Changing data validation default to disabled

photon-client/src/main/scala/com/linkedin/photon/ml/data/DataValidators.scala
The data validation code tried to pull the entire dataset into memory, as described in issue #306.
=> Fix issue #306 related to data validation code

photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/PoissonLossEvaluator.scala, photon-client/src/main/scala/com/linkedin/photon/ml/Driver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/ModelSelection.scala, photon-diagnostics/src/main/scala/com/linkedin/photon/ml/Evaluation.scala
- Logistic and Poisson log-likelhoods computed incorrectly
- Average computed incorrectly, causing stochastic behaviour
- The above resulted in a mismatch between the metrics reported for Poisson regression, and the ones used to choose the best model (both were wrong)
=> Fix bug causing log-likelihoods to be computed incorrectly.

photon-client/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriverIntegTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/io/scopt/ScoptParserHelpers.scala, photon-client/src/test/scala/com/linkedin/photon/ml/io/FeatureShardConfigurationTest.scala
=> Fix parsing bug for feature shard without feature bags

photon-api/src/integTest/scala/com/linkedin/photon/ml/estimators/GameEstimatorIntegTest.scala, photon-api/src/integTest/scala/com/linkedin/photon/ml/normalization/NormalizationContextIntegTest.scala, photon-api/src/integTest/scala/com/linkedin/photon/ml/supervised/BaseGLMTest.scala, photon-api/src/main/scala/com/linkedin/photon/ml/ModelTraining.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/OptimizerConfig.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/OptimizerFactory.scala, photon-api/src/main/scala/com/linkedin/photon/ml/util/GameTestUtils.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriverIntegTest.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/data/avro/ModelProcessingUtilsTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/Driver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/io/deprecated/AvroInputDataFormat.scala, photon-client/src/main/scala/com/linkedin/photon/ml/io/deprecated/InputDataFormat.scala, photon-diagnostics/src/integTest/scala/com/linkedin/photon/ml/diagnostics/fitting/FittingDiagnosticIntegTest.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/optimization/LBFGS.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/optimization/LBFGSB.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/optimization/OWLQN.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/optimization/Optimizer.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/optimization/TRON.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/optimization/LBFGSBTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/optimization/LBFGSTest.scala
Change list:
1. add LBFGSB class and unit test
2. remove constrainMap in LBFGS class and update its unit test
3. remove constrainMap in OWLQN class and update its unit test
=> add LBFGSB class and unit test; modify all the interfaces of LBFGS,OWLQN

photon-client/src/integTest/scala/com/linkedin/photon/ml/cli/game/scoring/GameScoringDriverIntegTest.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriverIntegTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/GameScoringDriver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/avro/NameAndTermFeatureBagsDriver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/index/FeatureIndexingDriver.scala
- Add missing calls to validateParams
- Add missing documentation to NameAndTermFeatureBagsDriver
- Fix FeatureIndexingDriver bug causing job failures
=> Minor fixes

photon-api/src/integTest/scala/com/linkedin/photon/ml/supervised/BinaryPredictionValidator.scala, photon-api/src/integTest/scala/com/linkedin/photon/ml/supervised/PredictionFiniteValidator.scala, photon-api/src/integTest/scala/com/linkedin/photon/ml/supervised/PredictionNonNegativeValidator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/AreaUnderROCCurveEvaluator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/AreaUnderROCCurveMultiEvaluator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/LogisticLossEvaluator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/MultiEvaluator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/PoissonLossEvaluator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/PrecisionAtKMultiEvaluator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/RMSEEvaluator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/SmoothedHingeLossEvaluator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/evaluation/SquaredLossEvaluator.scala, photon-api/src/main/scala/com/linkedin/photon/ml/supervised/classification/BinaryClassifier.scala, photon-api/src/main/scala/com/linkedin/photon/ml/supervised/classification/LogisticRegressionModel.scala, photon-api/src/main/scala/com/linkedin/photon/ml/supervised/classification/SmoothedHingeLossLinearSVMModel.scala, photon-api/src/main/scala/com/linkedin/photon/ml/supervised/model/GeneralizedLinearModel.scala, photon-api/src/main/scala/com/linkedin/photon/ml/supervised/regression/LinearRegressionModel.scala, photon-api/src/main/scala/com/linkedin/photon/ml/supervised/regression/PoissonRegressionModel.scala, photon-api/src/main/scala/com/linkedin/photon/ml/supervised/regression/Regression.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriver.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/evaluation/Evaluator.scala
See: http://www.artima.com/lejava/articles/equality.html
=> Define equality between Evaluators and fix related bug

photon-client/src/main/scala/com/linkedin/photon/ml/data/DataValidators.scala, photon-client/src/test/scala/com/linkedin/photon/ml/data/DataValidatorsTest.scala
Update the error messages in `DataValidators` to be more specific.
=> Update DataValidators error message

photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/estimators/GaussianProcessEstimatorTest.scala
This was failing on some machines
Note: This test is just a quick sanity check. We need to come up with a way to more rigourously test the estimator.
=> Update GaussianProcessEstimator test case

photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/search/GaussianProcessSearch.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/search/RandomSearch.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/search/GaussianProcessSearchTest.scala
The code change necessary for using prior data across different dataset to speed up autotuning. The code is backward compatible and tested.
=> Update to use prior data in autotuning

photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/hyperparameter/PriorDataReader.scala, photon-client/src/test/scala/com/linkedin/photon/ml/hyperparameter/PriorDataReaderTest.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/search/RandomSearch.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/search/GaussianProcessSearchTest.scala
1. Add new file PriorDataReader to contain a method getPriorData;
2. Change the signature of find function to take priorData as an extra argument.
=> Read prior data for hyperparameter autotuning

photon-api/src/integTest/scala/com/linkedin/photon/ml/model/GameModelIntegTest.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/GameConverters.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriverIntegTest.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/data/avro/AvroUtilsIntegTest.scala, photon-client/src/integTest/scala/com/linkedin/photon/ml/data/avro/ModelProcessingUtilsIntegTest.scala, photon-client/src/main/java/org/apache/spark/photon/AvroGenericArrayRegistrator.java, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/scoring/GameScoringDriver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/avro/AvroDataReader.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/avro/ModelProcessingUtils.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/search/RandomSearch.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/model/GameModel.scala
1. Would attempt to build index map using inefficient legacy code for coordinates with missing feature shard definitions
2. Would always attempt to load all coordinates from model
=> Fix three partial retraining bugs

photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/GameTrainingDriver.scala, photon-client/src/main/scala/com/linkedin/photon/ml/hyperparameter/PriorDataReader.scala, photon-client/src/test/scala/com/linkedin/photon/ml/hyperparameter/PriorDataReaderTest.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/EvaluationFunction.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/search/GaussianProcessSearch.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/search/RandomSearch.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/search/GaussianProcessSearchTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/search/RandomSearchTest.scala
@joshvfleming 
@basukinjal 
@cmjiang
=> Update hyper-parameter tuning API, documentation, and style

photon-all/build.gradle
=> Remove Snappy from the shaded jar

photon-avro-schemas/src/main/avro/ResponsePredictionAvro.avsc, photon-client/src/integTest/scala/com/linkedin/photon/ml/data/avro/AvroDataWriterIntegTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/avro/AvroDataWriter.scala, photon-client/src/test/scala/com/linkedin/photon/ml/data/avro/AvroDataWriterTest.scala
Add avrowriter servers as the counter part of `AvroDataReader`. @joshvfleming @ashelkovnykov
=> add avrowriter

photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/estimators/kernels/Matern52.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/estimators/kernels/RBF.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/estimators/kernels/StationaryKernel.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/search/GaussianProcessSearch.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/search/RandomSearch.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/estimators/kernels/StationaryKernelTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/search/GaussianProcessSearchTest.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/hyperparameter/search/RandomSearchTest.scala
@joshvfleming @basukinjal @ashelkovnykov Please review the code. Thanks.
=> Add hyper-parameter rescaling in covariance kernel

photon-client/src/main/scala/com/linkedin/photon/ml/data/avro/AvroDataWriter.scala, photon-client/src/test/scala/com/linkedin/photon/ml/data/avro/AvroDataWriterTest.scala
=> support null types for offset and weight

photon-client/src/integTest/scala/com/linkedin/photon/ml/data/avro/AvroDataWriterIntegTest.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/avro/AvroDataReader.scala, photon-client/src/main/scala/com/linkedin/photon/ml/data/avro/AvroDataWriter.scala, photon-client/src/main/scala/com/linkedin/photon/ml/util/IOUtils.scala, photon-client/src/test/scala/com/linkedin/photon/ml/data/avro/AvroDataWriterTest.scala
1. Fix the numPartition bug in `AvroDataReader`
2. Add rat in `AvroDataWriter`
3. open scope of `IOUtils`
=> [xs] Bug fix; add rat in AvroDataWriter; open scope of IOUtils

photon-client/src/main/scala/com/linkedin/photon/ml/io/scopt/ScoptParserHelpers.scala, photon-client/src/test/scala/com/linkedin/photon/ml/io/scopt/ScoptParserHelpersTest.scala
Previous code couldn't handle scientific notation or negative numbers
=> Fix DoubleRange parsing bug

photon-lib/src/main/scala/com/linkedin/photon/ml/algorithm/CoordinateDescent.scala
Comment describes what this line should actually be testing for.
=> Fix bug which will unpersist trained models incorrectly

.travis.yml, defaultEnvironment.gradle, photon-lib/src/test/scala/com/linkedin/photon/ml/util/ImplicitsTest.scala, settings.gradle, travis/tests.sh
Testing finished - crossbuilding now works on Travis
=> Enable Scala version 2.11.8 cross-building and Travis CI testing

photon-lib/src/main/scala/com/linkedin/photon/ml/optimization/TRON.scala
Added in very crude support for coefficient constraint maps in the TRON optimizer
This resolves #378
=> Added support for constraint maps in TRON optimizer

photon-client/src/main/scala/com/linkedin/photon/ml/hyperparameter/ShrinkSearchRange.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/hyperparameter/search/GaussianProcessSearch.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/util/DoubleRange.scala
This is a helper function to implement autotune with sub-sampling for machine learning models. This function takes hyperparameters and evaluation values, fits a Gaussian process regression model and outputs a small range which centers at the optimal value. It will be a part of atlas-ml hyperparameter tuning library.
=> shrink search range functionality added

photon-api/src/main/scala/com/linkedin/photon/ml/data/LocalDataset.scala, photon-api/src/test/scala/com/linkedin/photon/ml/data/LocalDatasetTest.scala
The commit fixes #50 by implementing the algorithm described in http://prod.sandia.gov/techlib/access-control.cgi/2008/086212.pdf - as suggested in the issue.
I also added a pathological test case that used to fail with the previous implementation due to numerical instability. The new implementation passes the test. See: `LocalDatasetTest.testPearsonCorrelationScoreStability`.
=> Implement numerically stable Pearson Correlation

photon-api/src/integTest/scala/com/linkedin/photon/ml/data/RandomEffectDatasetIntegTest.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/RandomEffectDataset.scala
This change greatly improves the executor memory usage during `RandomEffectDataset` construction - 50% reduction in my tests.
=> Improve effeciency of join during RandomEffectDataset construction

photon-api/src/integTest/scala/com/linkedin/photon/ml/data/RandomEffectDatasetIntegTest.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/RandomEffectDataset.scala
- Split existing integration test into two separate tests to check lower bound thresholding
- Added new integration test to make sure that data filtered by lower bound thresholding is not in passive data
=> Fix bug which would treat data filtered by the 'active.data.lower.bound' as passive data

photon-api/src/integTest/scala/com/linkedin/photon/ml/algorithm/FixedEffectCoordinateIntegTest.scala, photon-api/src/main/scala/com/linkedin/photon/ml/algorithm/RandomEffectCoordinate.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/FixedEffectDataset.scala, photon-api/src/main/scala/com/linkedin/photon/ml/data/RandomEffectDataset.scala, photon-api/src/main/scala/com/linkedin/photon/ml/model/RandomEffectModel.scala, photon-api/src/main/scala/com/linkedin/photon/ml/optimization/game/RandomEffectOptimizationProblem.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/constants/MathConst.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/data/GameDatum.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/data/scoring/CoordinateDataScores.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/data/scoring/DataScores.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/data/scoring/ModelDataScores.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/data/scoring/ScoredGameDatum.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/evaluation/EvaluationSuite.scala, photon-lib/src/main/scala/com/linkedin/photon/ml/evaluation/MultiEvaluator.scala, photon-lib/src/test/scala/com/linkedin/photon/ml/data/scoring/ScoredGameDatumTest.scala
- Fix join issues
- Document joins, make it easier to understand why we join RDDs as we do
- Remove unused projectors after applying data lower bound threshold
=> RDD join refactor

photon-api/src/main/scala/com/linkedin/photon/ml/model/RandomEffectModel.scala
=> Loosen permissions on raw RDD of models in RandomEffectModel

photon-api/src/main/scala/com/linkedin/photon/ml/algorithm/RandomEffectCoordinate.scala
trainModel function in `RandomEffectCoordinate` has a bug when prior models are involved. Since left join is used, any data with random effect ids not in prior models will be dropped. Therefore there is no model trained for that data.
This PR changes left join to outer join.
=> Change left to outer join when joining models and data

CHANGELOG.md, build.gradle, jcenter/bintray.gradle, release-bintray.gradle
1. Change the artifact groupId to 'com.linkedin.li-photon-ml' to prevent potential dependency conflict resolution issue;
2. Change default bintray 'override' value to be false;
3. Add CHANGELOG.md.
=> Change the artifact groupId to 'com.linkedin.li-photon-ml' and add CHANGELOG.md
